### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by martinmladenov**
Updating dependencies currently causes some unit tests to fail:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CodeChecksTest.allChecksPass:16 
Expecting actual:
  Result{compilation=CompilationResult{errors=[CompilationErrorInfo{fileName='/tmp/1635282971973-0/delft/Solution.java', lineNumber=5, message='cannot find symbol
  symbol:   class Matchers
  location: package org.mockito'}], configurationError=false, wasExecuted=true}, tests=UnitTestsResult{testsFound=0, testsRan=0, testsSucceeded=0, failures=[], console='null', wasExecuted=false}, mutationTesting=MutationTestingResult{wasExecuted=false, killedMutants=0, totalNumberOfMutants=0}, codeChecks=CodeChecksResult{wasExecuted=false, checkResults=[]}, coverage=CoverageResult{wasExecuted=false, totalCoveredLines=0, totalLines=0, totalCoveredInstructions=0, totalInstructions=0, totalCoveredBranches=0, totalBranches=0, coverageLineByLine=CoverageLineByLine{fullyCoveredLines=[], partiallyCoveredLines=[], notCoveredLines=[]}}, metaTests=MetaTestsResult{wasExecuted=false, score=0, totalTests=0, metaTestResults=[]}, finalGrade=0, genericFailure='null', timeInSeconds=0.172052704, weights=null}
to have 
[ERROR]   CodeChecksTest.someChecksFail:27 
Expecting actual:
  Result{compilation=CompilationResult{errors=[CompilationErrorInfo{fileName='/tmp/1635282972311-0/delft/Solution.java', lineNumber=5, message='cannot find symbol
  symbol:   class Matchers
  location: package org.mockito'}], configurationError=false, wasExecuted=true}, tests=UnitTestsResult{testsFound=0, testsRan=0, testsSucceeded=0, failures=[], console='null', wasExecuted=false}, mutationTesting=MutationTestingResult{wasExecuted=false, killedMutants=0, totalNumberOfMutants=0}, codeChecks=CodeChecksResult{wasExecuted=false, checkResults=[]}, coverage=CoverageResult{wasExecuted=false, totalCoveredLines=0, totalLines=0, totalCoveredInstructions=0, totalInstructions=0, totalCoveredBranches=0, totalBranches=0, coverageLineByLine=CoverageLineByLine{fullyCoveredLines=[], partiallyCoveredLines=[], notCoveredLines=[]}}, metaTests=MetaTestsResult{wasExecuted=false, score=0, totalTests=0, metaTestResults=[]}, finalGrade=0, genericFailure='null', timeInSeconds=0.114486576, weights=null}
to have 
[ERROR]   JUnitTestsTest$GeneralMistakes.mockitoAssertionFailing:205 
expected: 2
 but was: 0
[ERROR]   JUnitTestsTest$GeneralMistakes.stubbingNonMockClass:218 
expected: 2
 but was: 0
[ERROR]   JUnitTestsTest$Mockito.mocksWork:77 
expected: 3
 but was: 0
[ERROR]   JacocoTest.differentCoverages:24 
Expecting value to be true but was false
[ERROR]   MetaTestsTest.testMetaWhenMultipleClassesInLibrary:58 
expected: 4
 but was: 0
[ERROR]   ModesAndActionsTest.gradingModeShouldRunEverything:74 
expected: 2
 but was: 0
[ERROR]   ModesAndActionsTest.gradingModeShouldRunEverything:74 
expected: 2
 but was: 0
[ERROR]   ModesAndActionsTest.gradingModeShouldRunEverything:74 
expected: 2
 but was: 0
[ERROR]   ModesAndActionsTest.practiceModeRunsEverything:19 
expected: 2
 but was: 0
[ERROR]   ModesAndActionsTest.runOnlyTests:38 
Expecting value to be true but was false
[ERROR]   ModesAndActionsTest.runOnlyTestsAndCoverageToolsDuringExam:53 
Expecting value to be true but was false
[ERROR]   PitestTest.allMutantsButOneKilled:19 
expected: 32
 but was: 0
[ERROR]   PitestTest.mutantsSurvived:30 
expected: 7
 but was: 0
[INFO] 
[ERROR] Tests run: 290, Failures: 15, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by Arraying** [comment]
Selenium has been updated to version 4 in our `fix-selenium` branch AFAIK. Are any of these updates mission critical? Otherwise, I suggest we close this, for now, and then reconsider updating all non-critical dependencies once Andy has shown stability with the many changes we have made recently.

**Comment by mauricioaniche** [comment]
I do not think any of these are mission critical. Updating JUnit also means pitest needs to update, so we are bounded by their version anyways. Mockito and JDT are the only ones I can think of that would be nice to bump.

**Comment by Arraying** [comment]
> I do not think any of these are mission critical. Updating JUnit also means pitest needs to update, so we are bounded by their version anyways. Mockito and JDT are the only ones I can think of that would be nice to bump.

I think we need Selenium 4.0.0 for our fancy petclinic to work but you are right. Let's close this for now and then bump Mockito and JDT later?

**Comment by mauricioaniche** [comment]
Oh yeah, I meant besides Selenium 4. Bumping Mockito and JDT should not break anything, so we might as well just bump them now. Leave the others for the future.

**Comment by Arraying** [comment]
Okay, I will bump these on the Selenium branch and close this, for now.

**Comment by mauricioaniche** [comment]
I said Mockito would not break anything, but I actually don't know if pitest shadows it too. We have to try :/

**Comment by Arraying** [comment]
Upgrading to Mockito 4 [(which should not break)](https://twitter.com/MockitoJava/status/1446121357280903181) caused 13 tests to fail. Similarly, the latest version 3 also failed 13. I fear you may be right, I can debug it later but for now I don't think that should be a priority. Sticking with the current version for now!

**Pull request closed without merging**
