### PR TITLE
Add more reflection keywords

### PR DESCRIPTION
**Pull request by martinmladenov**
Added some more keywords suggested by @Arraying in order to improve detection of reflection usage

### CODE REVIEW

**Comment by Arraying** [comment]
Missing:
* `getConstructors`
* `getDeclaredAnnotations`
* `getDeclaredConstructors`
* `getDeclaredFields`
* `getFields`
* `getMethods`

Without these blocked it could still be possible to perform some reflection.

**Review by Arraying — CHANGES_REQUESTED** [review]
See my other comment.

**Comment by martinmladenov** [comment]
@Arraying 
> Missing:
> 
>     * `getConstructors`
> 
>     * `getDeclaredAnnotations`
> 
>     * `getDeclaredConstructors`
> 
>     * `getDeclaredFields`
> 
>     * `getFields`
> 
>     * `getMethods`
> 
> 
> Without these blocked it could still be possible to perform some reflection.

Those are blocked too since we do a simple string comparison. For example, adding `getField` to the list means `getFields` is automatically also blocked.

**Review by Arraying — APPROVED** [review]
Looks good then :)

**Pull request merged**
